// Code generated by ent, DO NOT EDIT.

package sporesyringe

import (
	"time"
)

const (
	// Label holds the string label denoting the sporesyringe type in the database.
	Label = "spore_syringe"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRecievedDate holds the string denoting the recieveddate field in the database.
	FieldRecievedDate = "recieved_date"
	// FieldSpecies holds the string denoting the species field in the database.
	FieldSpecies = "species"
	// FieldSupplier holds the string denoting the supplier field in the database.
	FieldSupplier = "supplier"
	// EdgeGrainJars holds the string denoting the grainjars edge name in mutations.
	EdgeGrainJars = "grainJars"
	// Table holds the table name of the sporesyringe in the database.
	Table = "spore_syringes"
	// GrainJarsTable is the table that holds the grainJars relation/edge.
	GrainJarsTable = "grain_jars"
	// GrainJarsInverseTable is the table name for the GrainJar entity.
	// It exists in this package in order to avoid circular dependency with the "grainjar" package.
	GrainJarsInverseTable = "grain_jars"
	// GrainJarsColumn is the table column denoting the grainJars relation/edge.
	GrainJarsColumn = "spore_syringe_grain_jars"
)

// Columns holds all SQL columns for sporesyringe fields.
var Columns = []string{
	FieldID,
	FieldRecievedDate,
	FieldSpecies,
	FieldSupplier,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultRecievedDate holds the default value on creation for the "RecievedDate" field.
	DefaultRecievedDate func() time.Time
	// DefaultSpecies holds the default value on creation for the "Species" field.
	DefaultSpecies string
	// DefaultSupplier holds the default value on creation for the "Supplier" field.
	DefaultSupplier string
)
