// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// GrainJarsColumns holds the columns for the "grain_jars" table.
	GrainJarsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "innoculation_date", Type: field.TypeTime},
		{Name: "grain", Type: field.TypeString, Default: "unknown"},
		{Name: "harvest_date", Type: field.TypeTime},
	}
	// GrainJarsTable holds the schema information for the "grain_jars" table.
	GrainJarsTable = &schema.Table{
		Name:       "grain_jars",
		Columns:    GrainJarsColumns,
		PrimaryKey: []*schema.Column{GrainJarsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		GrainJarsTable,
	}
)

func init() {
}
