// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"example/myco-api/ent/grainjar"
	"example/myco-api/ent/predicate"
	"example/myco-api/ent/sporesyringe"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SporeSyringeQuery is the builder for querying SporeSyringe entities.
type SporeSyringeQuery struct {
	config
	ctx          *QueryContext
	order        []OrderFunc
	inters       []Interceptor
	predicates   []predicate.SporeSyringe
	withGrainJar *GrainJarQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SporeSyringeQuery builder.
func (ssq *SporeSyringeQuery) Where(ps ...predicate.SporeSyringe) *SporeSyringeQuery {
	ssq.predicates = append(ssq.predicates, ps...)
	return ssq
}

// Limit the number of records to be returned by this query.
func (ssq *SporeSyringeQuery) Limit(limit int) *SporeSyringeQuery {
	ssq.ctx.Limit = &limit
	return ssq
}

// Offset to start from.
func (ssq *SporeSyringeQuery) Offset(offset int) *SporeSyringeQuery {
	ssq.ctx.Offset = &offset
	return ssq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ssq *SporeSyringeQuery) Unique(unique bool) *SporeSyringeQuery {
	ssq.ctx.Unique = &unique
	return ssq
}

// Order specifies how the records should be ordered.
func (ssq *SporeSyringeQuery) Order(o ...OrderFunc) *SporeSyringeQuery {
	ssq.order = append(ssq.order, o...)
	return ssq
}

// QueryGrainJar chains the current query on the "grainJar" edge.
func (ssq *SporeSyringeQuery) QueryGrainJar() *GrainJarQuery {
	query := (&GrainJarClient{config: ssq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ssq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ssq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(sporesyringe.Table, sporesyringe.FieldID, selector),
			sqlgraph.To(grainjar.Table, grainjar.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, sporesyringe.GrainJarTable, sporesyringe.GrainJarColumn),
		)
		fromU = sqlgraph.SetNeighbors(ssq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SporeSyringe entity from the query.
// Returns a *NotFoundError when no SporeSyringe was found.
func (ssq *SporeSyringeQuery) First(ctx context.Context) (*SporeSyringe, error) {
	nodes, err := ssq.Limit(1).All(setContextOp(ctx, ssq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{sporesyringe.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ssq *SporeSyringeQuery) FirstX(ctx context.Context) *SporeSyringe {
	node, err := ssq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SporeSyringe ID from the query.
// Returns a *NotFoundError when no SporeSyringe ID was found.
func (ssq *SporeSyringeQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ssq.Limit(1).IDs(setContextOp(ctx, ssq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{sporesyringe.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ssq *SporeSyringeQuery) FirstIDX(ctx context.Context) int {
	id, err := ssq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SporeSyringe entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SporeSyringe entity is found.
// Returns a *NotFoundError when no SporeSyringe entities are found.
func (ssq *SporeSyringeQuery) Only(ctx context.Context) (*SporeSyringe, error) {
	nodes, err := ssq.Limit(2).All(setContextOp(ctx, ssq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{sporesyringe.Label}
	default:
		return nil, &NotSingularError{sporesyringe.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ssq *SporeSyringeQuery) OnlyX(ctx context.Context) *SporeSyringe {
	node, err := ssq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SporeSyringe ID in the query.
// Returns a *NotSingularError when more than one SporeSyringe ID is found.
// Returns a *NotFoundError when no entities are found.
func (ssq *SporeSyringeQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ssq.Limit(2).IDs(setContextOp(ctx, ssq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{sporesyringe.Label}
	default:
		err = &NotSingularError{sporesyringe.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ssq *SporeSyringeQuery) OnlyIDX(ctx context.Context) int {
	id, err := ssq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SporeSyringes.
func (ssq *SporeSyringeQuery) All(ctx context.Context) ([]*SporeSyringe, error) {
	ctx = setContextOp(ctx, ssq.ctx, "All")
	if err := ssq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SporeSyringe, *SporeSyringeQuery]()
	return withInterceptors[[]*SporeSyringe](ctx, ssq, qr, ssq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ssq *SporeSyringeQuery) AllX(ctx context.Context) []*SporeSyringe {
	nodes, err := ssq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SporeSyringe IDs.
func (ssq *SporeSyringeQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	ctx = setContextOp(ctx, ssq.ctx, "IDs")
	if err := ssq.Select(sporesyringe.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ssq *SporeSyringeQuery) IDsX(ctx context.Context) []int {
	ids, err := ssq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ssq *SporeSyringeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ssq.ctx, "Count")
	if err := ssq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ssq, querierCount[*SporeSyringeQuery](), ssq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ssq *SporeSyringeQuery) CountX(ctx context.Context) int {
	count, err := ssq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ssq *SporeSyringeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ssq.ctx, "Exist")
	switch _, err := ssq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ssq *SporeSyringeQuery) ExistX(ctx context.Context) bool {
	exist, err := ssq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SporeSyringeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ssq *SporeSyringeQuery) Clone() *SporeSyringeQuery {
	if ssq == nil {
		return nil
	}
	return &SporeSyringeQuery{
		config:       ssq.config,
		ctx:          ssq.ctx.Clone(),
		order:        append([]OrderFunc{}, ssq.order...),
		inters:       append([]Interceptor{}, ssq.inters...),
		predicates:   append([]predicate.SporeSyringe{}, ssq.predicates...),
		withGrainJar: ssq.withGrainJar.Clone(),
		// clone intermediate query.
		sql:  ssq.sql.Clone(),
		path: ssq.path,
	}
}

// WithGrainJar tells the query-builder to eager-load the nodes that are connected to
// the "grainJar" edge. The optional arguments are used to configure the query builder of the edge.
func (ssq *SporeSyringeQuery) WithGrainJar(opts ...func(*GrainJarQuery)) *SporeSyringeQuery {
	query := (&GrainJarClient{config: ssq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ssq.withGrainJar = query
	return ssq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		RecievedDate time.Time `json:"RecievedDate,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SporeSyringe.Query().
//		GroupBy(sporesyringe.FieldRecievedDate).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ssq *SporeSyringeQuery) GroupBy(field string, fields ...string) *SporeSyringeGroupBy {
	ssq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SporeSyringeGroupBy{build: ssq}
	grbuild.flds = &ssq.ctx.Fields
	grbuild.label = sporesyringe.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		RecievedDate time.Time `json:"RecievedDate,omitempty"`
//	}
//
//	client.SporeSyringe.Query().
//		Select(sporesyringe.FieldRecievedDate).
//		Scan(ctx, &v)
func (ssq *SporeSyringeQuery) Select(fields ...string) *SporeSyringeSelect {
	ssq.ctx.Fields = append(ssq.ctx.Fields, fields...)
	sbuild := &SporeSyringeSelect{SporeSyringeQuery: ssq}
	sbuild.label = sporesyringe.Label
	sbuild.flds, sbuild.scan = &ssq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SporeSyringeSelect configured with the given aggregations.
func (ssq *SporeSyringeQuery) Aggregate(fns ...AggregateFunc) *SporeSyringeSelect {
	return ssq.Select().Aggregate(fns...)
}

func (ssq *SporeSyringeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ssq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ssq); err != nil {
				return err
			}
		}
	}
	for _, f := range ssq.ctx.Fields {
		if !sporesyringe.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ssq.path != nil {
		prev, err := ssq.path(ctx)
		if err != nil {
			return err
		}
		ssq.sql = prev
	}
	return nil
}

func (ssq *SporeSyringeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SporeSyringe, error) {
	var (
		nodes       = []*SporeSyringe{}
		_spec       = ssq.querySpec()
		loadedTypes = [1]bool{
			ssq.withGrainJar != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SporeSyringe).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SporeSyringe{config: ssq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ssq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := ssq.withGrainJar; query != nil {
		if err := ssq.loadGrainJar(ctx, query, nodes,
			func(n *SporeSyringe) { n.Edges.GrainJar = []*GrainJar{} },
			func(n *SporeSyringe, e *GrainJar) { n.Edges.GrainJar = append(n.Edges.GrainJar, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ssq *SporeSyringeQuery) loadGrainJar(ctx context.Context, query *GrainJarQuery, nodes []*SporeSyringe, init func(*SporeSyringe), assign func(*SporeSyringe, *GrainJar)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*SporeSyringe)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.GrainJar(func(s *sql.Selector) {
		s.Where(sql.InValues(sporesyringe.GrainJarColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.spore_syringe_grain_jar
		if fk == nil {
			return fmt.Errorf(`foreign-key "spore_syringe_grain_jar" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "spore_syringe_grain_jar" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (ssq *SporeSyringeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ssq.querySpec()
	_spec.Node.Columns = ssq.ctx.Fields
	if len(ssq.ctx.Fields) > 0 {
		_spec.Unique = ssq.ctx.Unique != nil && *ssq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ssq.driver, _spec)
}

func (ssq *SporeSyringeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   sporesyringe.Table,
			Columns: sporesyringe.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: sporesyringe.FieldID,
			},
		},
		From:   ssq.sql,
		Unique: true,
	}
	if unique := ssq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := ssq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sporesyringe.FieldID)
		for i := range fields {
			if fields[i] != sporesyringe.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ssq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ssq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ssq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ssq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ssq *SporeSyringeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ssq.driver.Dialect())
	t1 := builder.Table(sporesyringe.Table)
	columns := ssq.ctx.Fields
	if len(columns) == 0 {
		columns = sporesyringe.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ssq.sql != nil {
		selector = ssq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ssq.ctx.Unique != nil && *ssq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ssq.predicates {
		p(selector)
	}
	for _, p := range ssq.order {
		p(selector)
	}
	if offset := ssq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ssq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SporeSyringeGroupBy is the group-by builder for SporeSyringe entities.
type SporeSyringeGroupBy struct {
	selector
	build *SporeSyringeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ssgb *SporeSyringeGroupBy) Aggregate(fns ...AggregateFunc) *SporeSyringeGroupBy {
	ssgb.fns = append(ssgb.fns, fns...)
	return ssgb
}

// Scan applies the selector query and scans the result into the given value.
func (ssgb *SporeSyringeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ssgb.build.ctx, "GroupBy")
	if err := ssgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SporeSyringeQuery, *SporeSyringeGroupBy](ctx, ssgb.build, ssgb, ssgb.build.inters, v)
}

func (ssgb *SporeSyringeGroupBy) sqlScan(ctx context.Context, root *SporeSyringeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ssgb.fns))
	for _, fn := range ssgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ssgb.flds)+len(ssgb.fns))
		for _, f := range *ssgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ssgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ssgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SporeSyringeSelect is the builder for selecting fields of SporeSyringe entities.
type SporeSyringeSelect struct {
	*SporeSyringeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (sss *SporeSyringeSelect) Aggregate(fns ...AggregateFunc) *SporeSyringeSelect {
	sss.fns = append(sss.fns, fns...)
	return sss
}

// Scan applies the selector query and scans the result into the given value.
func (sss *SporeSyringeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sss.ctx, "Select")
	if err := sss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SporeSyringeQuery, *SporeSyringeSelect](ctx, sss.SporeSyringeQuery, sss, sss.inters, v)
}

func (sss *SporeSyringeSelect) sqlScan(ctx context.Context, root *SporeSyringeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(sss.fns))
	for _, fn := range sss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*sss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
