// Code generated by ent, DO NOT EDIT.

package grainjar

import (
	"time"
)

const (
	// Label holds the string label denoting the grainjar type in the database.
	Label = "grain_jar"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldInnoculationDate holds the string denoting the innoculationdate field in the database.
	FieldInnoculationDate = "innoculation_date"
	// FieldGrain holds the string denoting the grain field in the database.
	FieldGrain = "grain"
	// FieldHarvestDate holds the string denoting the harvestdate field in the database.
	FieldHarvestDate = "harvest_date"
	// EdgeSporeSyringe holds the string denoting the sporesyringe edge name in mutations.
	EdgeSporeSyringe = "sporeSyringe"
	// Table holds the table name of the grainjar in the database.
	Table = "grain_jars"
	// SporeSyringeTable is the table that holds the sporeSyringe relation/edge.
	SporeSyringeTable = "spore_syringes"
	// SporeSyringeInverseTable is the table name for the SporeSyringe entity.
	// It exists in this package in order to avoid circular dependency with the "sporesyringe" package.
	SporeSyringeInverseTable = "spore_syringes"
	// SporeSyringeColumn is the table column denoting the sporeSyringe relation/edge.
	SporeSyringeColumn = "grain_jar_spore_syringe"
)

// Columns holds all SQL columns for grainjar fields.
var Columns = []string{
	FieldID,
	FieldInnoculationDate,
	FieldGrain,
	FieldHarvestDate,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultInnoculationDate holds the default value on creation for the "InnoculationDate" field.
	DefaultInnoculationDate func() time.Time
	// DefaultGrain holds the default value on creation for the "Grain" field.
	DefaultGrain string
)
