// Code generated by ent, DO NOT EDIT.

package grainjar

import (
	"time"
)

const (
	// Label holds the string label denoting the grainjar type in the database.
	Label = "grain_jar"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldInnoculationDate holds the string denoting the innoculationdate field in the database.
	FieldInnoculationDate = "innoculation_date"
	// FieldGrain holds the string denoting the grain field in the database.
	FieldGrain = "grain"
	// FieldHarvestDate holds the string denoting the harvestdate field in the database.
	FieldHarvestDate = "harvest_date"
	// Table holds the table name of the grainjar in the database.
	Table = "grain_jars"
)

// Columns holds all SQL columns for grainjar fields.
var Columns = []string{
	FieldID,
	FieldInnoculationDate,
	FieldGrain,
	FieldHarvestDate,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "grain_jars"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"spore_syringe_grain_jar",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultInnoculationDate holds the default value on creation for the "InnoculationDate" field.
	DefaultInnoculationDate func() time.Time
	// DefaultGrain holds the default value on creation for the "Grain" field.
	DefaultGrain string
)
