name: learn-github-actions

run-name: ${{ github.actor }} is learning GitHub Actions
on:
  workflow_dispatch:
    inputs:
      cosign_release:
        required: false
        description: "Cosign release version (e.g. 'v2.0.0')"
        type: string
        default: ""
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    env:
      Release: 1
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      - run: echo ${{ startsWith(inputs.cosign_release, "1.") && \\"1\\" || \\"0\\" }}
